### ISSUE TITLE
Add Officially Endorsed Flatpak to README

### ISSUE THREAD

**Issue by StandingPadAnimations** [tkaczz/org.bforartists.Bforartists#5]
Bforartists now has a Flatpak version (albeit unofficially maintained by myself, but endorsed) available on Flathub. It'd be best if you add some info redirecting users to the officially endorsed Bforartists Flatpak in the README.

https://github.com/flathub/de.bforartists.Bforartists

**Comment by tkaczz** [comment]
Hi, okay I'll do that.
